### ISSUE TITLE
Access my workplace intranet with a wrapper/mirror website resides on my vps.

### ISSUE THREAD

**Issue by hongyi-zhao** [kasattejaswi/nodejs-proxy-server#3]
I noticed this wonderful and concise nodejs project. But my current situation is as follows: I've a VPS bound to the domain my.domain.xyz. At the meanwhile, a socks5 proxy server runs on the VPS and listens on port 1080 which can access the website located on my office subnet, say, by starting chrome with the following command:

`$ google-chrome --proxy-server="socks5://my.domain.xyz:1080"`

Then I can access my workplace intranet by the following URL:

`http://10.10.10.10:2021`

This way works, but some cumbersome settings are required. I want to access my workplace intranet with a wrapper/mirror website resides on my VPS, say, http://my.domain.xyz:21080, which can access the intranet website via the socks5 proxy server mentioned above. I mean, when I open the URL http://my.domain.xyz:21080 from anywhere outside the workplace intranet, it will automatically be redirected to http://10.10.10.10:2021 via the socks5 proxy server "socks5://my.domain.xyz:1080".

Is there a feasible way to achieve this aim with the help of JavaScript?

Regards,
HZ

**Comment by kasattejaswi** [comment]
This is something related to reverse proxy setup. Need to think about it. The current project covers forward proxy.
