### ISSUE TITLE
Error "TCP.onStreamRead"

### ISSUE THREAD

**Issue by hamadaDev** [kasattejaswi/nodejs-proxy-server#5]
hi 
I face this error when try  as Examble update vscode or try update visual studio 

=========================================
```
Proxy to server error
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
```
=======================================
If you can updaye it or any ideya to Solve this problem
thank's

**Comment by kasattejaswi** [comment]
Where you're trying to run it ?
