### ISSUE TITLE
Implementation of load balancing to the current application

### ISSUE THREAD

**Issue by onukwilip** [kasattejaswi/nodejs-proxy-server#7]
Hello there 👋🏾! My name is Prince. I saw your article on creating a custom proxy server on [https://plainenglish.io/blog/build-your-own-forward-and-reverse-proxy-server-using-node-js-from-scratch-eaa0f8d69e1f](https://plainenglish.io/blog/build-your-own-forward-and-reverse-proxy-server-using-node-js-from-scratch-eaa0f8d69e1f) and I loved it. But, I have one question. I'm developing software and want to implement load-balancing (already handled the algorithm for that), but i want to implement a logic in which - if a client specifies multiple servers for load-balancing and the application can't connect to one of them, it should automatically route to one of the other specified servers. I want to know how to send another request to another server if the one initially specified can't be connected to. I've tried using `proxyToServerSocket.pipe(clientToProxyServer)` again with another host and port, but it isn't working.

Thank you in advance!

**Comment by kasattejaswi** [comment]
When we talk about load balancing, there are more components involved than just a proxy. The most important one is the health check. So, you can define this as below:

Create a config file - in YAML or JSON format, where you can define what are your target hosts, on what port a service is running, and what is endpoint the load balancer should call to understand if service is running or not. A simple example: Suppose you have an application running on some internal hosts 192.168.10.10 and 192.168.10.12 and ports 8080 on each of those hosts. You can define a config file as below:
```json
{
  "hostGroups": [
    {
      "host": "192.168.10.10",
      "port": "8080",
      "healthEndpoint": {
        "protocol": "TCP",
        "path": "/health",
        "successCode": "200",
        "interval": 20
      },
      "pingTimesTillFailure": 10
    },
    {
      "host": "192.168.10.11",
      "port": "8080",
      "healthEndpoint": {
        "protocol": "TCP",
        "path": "/health",
        "successCode": "200",
        "interval": 20
      },
      "pingTimesTillFailure": 10
    }
  ]
}
``` 
You can write a code to read this file and understand the method on how to consider the failure of service. Field `interval` defines how much time in seconds the load balancer should ping this host. Field `pingTimesTillFailure` defines how many times your load balancer should hit the defined service with fail response till it considers it as down. As per the above config, If host A is returning 500 or any other responses 10 times in 20 seconds intervals, it will be marked as down.

Based on the above logic, you can understand to which host you should send the request. If both hosts are up, you can use any algorithms like RoundRobin to understand which host to forward the request to. If any of the hosts is down, you can use the above login to forward the request.

**Comment by kasattejaswi** [comment]
@onukwilip If you wish to implement the logic in this repository, you're most welcome to contribute.

**Comment by onukwilip** [comment]
Thank you so much! I really appreciate! This would be so helpful!!! 😃

**Comment by onukwilip** [comment]
I'll be sure to contribute if I implement the feature successfully! Thanks again 🙏

**Comment by kasattejaswi** [comment]
Great. You're welcome!

**Comment by kasattejaswi** [comment]
Hi @onukwilip, I have implemented a new load balancer. It has basic implementation that you can use: https://github.com/kasattejaswi/glb

**Comment by onukwilip** [comment]
Thank you, dude! But, I implemented the first solution you gave me, and it
worked perfectly fine. Thanks again!
